language: python

addons:
  sonarcloud:
    organization: "aimerfan"
    token:
      secure: $SC_TOKEN

install:
  - pip install django

before_script:
  - python manage.py migrate

script:
  - python manage.py test
  - sonar-scanner -Dsonar.login=$SC_TOKEN
