language: python

addons:
  sonarcloud:
    organization: "aimerfan"
    token:
      secure: $SC_TOKEN

install:
  - pip install django
  - pip install coverage

before_script:
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test
  - coverage xml
  - sonar-scanner -Dsonar.login=$SC_TOKEN
